### ISSUE TITLE
Day15-TimeSeries

### ISSUE THREAD

**Issue by bigpas** [DataWookie/MonthOfJulia#1]
Hi, 

please, check out the second code snippet from [Day 15](http://www.exegetic.biz/blog/2015/09/monthofjulia-day-15-time-series/)

best,

**Comment by datawookie** [comment]
Hi bigpas,

Thanks for bringing that to my attention. Nice to know that somebody is reading this stuff! I assume that you were referring to the numerous funky `&quot;`s, right? Looks like my code formatter let me down. I have fixed the issue.

Best regards,
Andrew.
