### ISSUE TITLE
Day 30: Clustering DBSCAN results

### ISSUE THREAD

**Issue by timothymillar** [DataWookie/MonthOfJulia#2]
Hi, I believe your interpretation/explanation of the DBSCAN results is misleading. DBSCAN can identify points as 'noise' and not assign them to a cluster at all, see [wikipedia](https://en.wikipedia.org/wiki/DBSCAN).

The blue points labeled as 0 are noise points and therefore have not "been lumped together into a single cluster". Similarly, Pythons sklearn will label noise points as -1. In your case, you could get a similar result to k-means by increasing the _eps_ value significantly. 

Regards, Tim.

**Comment by datawookie** [comment]
Hi Tim,

Thanks for the note. DBSCAN is not something that I have worked with before, so I was a little sketchy on the details. I have updated the post accordingly. I appreciate your putting me right!

Best regards, Andrew.
