### ISSUE TITLE
Blog links are broken again

### ISSUE THREAD

**Issue by alexcanepa** [DataWookie/MonthOfJulia#20]
Basically #16  again. Looks like the website doesn't have blog posts anymore, perhaps we should update the links to the [Internet Archive versions](https://web.archive.org/web/20180510202718/https://www.exegetic.biz/blog/2015/08/monthofjulia-day-01-installation-and-orientation/) or something similar?

**Comment by datawookie** [comment]
Thanks for bringing this to my attention. Changed the structure of my blog. All links from main page on GitHub should be fixed now.
