### ISSUE TITLE
In moj-04-functions.jl PARAMETRIC TYPES not working

### ISSUE THREAD

**Issue by dvstter** [DataWookie/MonthOfJulia#21]
When I am writing
`function sametype{T}(x::T, y::T)
    println("$x and $y are of the same type")
end`
the REPL give me sametype is Undef Error, could you please tell me your Julia version?
I am using v1.3

**Comment by datawookie** [comment]
These articles were written a *long* time ago. Check out https://datawookie.netlify.com/blog/2015/08/monthofjulia-day-1-installation-and-orientation/. I was running Julia v 0.3.10. The language has changed appreciably since then!

**Comment by dvstter** [comment]
Ok, Thanks. Could you please recommend some post or book about Julia. The official guide is so tedious, I want to use it as soon as possible. In fact I am a little familiar about C\C++, Python.
